### ISSUE TITLE
add print strings

### ISSUE THREAD

**Issue by tmgreenfield1101** [Ulvetanna/QuakeMigrate#2]
Add magic methods to some functions/objects to ease useability

**Comment by Ulvetanna** [comment]
def __str__(self):
   '''
        STUFF GOES HERE 
   '''

**Comment by hemmelig** [comment]
Magic method__str__() returns a printable string representation of any user defined class when str(object) is called.

**Comment by tmgreenfield1101** [comment]
I ahve a print string suggestion for class LUT

    def _str(self, good):
        if good:
            return '''
\tQuakeMigrate travel time look up table
\t\tGrid centre is\t:\t{lat:10.5f}\u00b0N, {lon:10.5f}\u00b0E, {dep:6.3f} km
\t\tNumber of cells\t:\t{0:4d}, {1:4d}, {2:4d}
\t\tCell Size\t:\t{3:6.3f} km, {4:6.3f} km, {5:6.3f} km
\t\t1D velocity model:
\t\t\t{6:>6s}\t{7:>6s}\t{8:>6s}
'''
        else:
            return '''
\tQuakeMigrate travel time look up table
\t\tGrid centre is\t:\t
\t\tNumber of cells\t:\t
\t\tCell Size\t:\t
\t\t1D velocity model:
\t\t\t{0:>6s}\t{1:>6s}\t{2:>6s}
'''

    def __str__(self):

        if not self.latitude:
            s = self._str(False)
            s = s.format('Depth', 'Vp', 'Vs')
        else:
            s = self._str(True)
            s = s.format(self.cell_count[0], self.cell_count[1], self.cell_count[2],
                        self.cell_size[0] / 1000., self.cell_size[1] / 1000., self.cell_size[2] / 1000.,
                        'Depth', 'Vp', 'Vs',
                        lat=self.latitude, lon=self.longitude, dep=self.elevation / 1000.)

            nlayer = len(self.velocity_model['depth'])
            i = 0
            vstring = '\n\t\t\t{0:6.3f}\t{1:6.3f}\t{2:6.3f}'
            while i < nlayer:
                s += vstring.format(self.velocity_model['depth'][i] / 1000.,
                                    self.velocity_model['vp'][i] / 1000.,
                                    self.velocity_model['vs'][i] / 1000.)
                i += 1
        return s

**Comment by hemmelig** [comment]
Print string suggestion for class mSEED:
Host path
Path structure
Sampling rate
Start time
End time

```
def __str__(self):
    """
    Return short summary string of the mSEED object

    It will provide information about the archive location and structure, data sampling rate
    and time period over which the archive is being queried.

    """

    out = QuakeMigrate mSEED object
    out = out + "\n".join("\tHost path\t:\t{}")
    out = out + "\n".join("\tPath structure\t:\t{}")
    out = out + "\n".join("\tSampling rate\t:\t{}")
    out = out + "\n".join("\tStart time\t:\t{}")
    out = out + "\n".join("\tEnd time\t:\t{}")
    out = out + "\n".join("\tStations:")
    for station in self.stations:
        out = out + "\n".join(\t\t{}).format(station)

    return out
```

On initialisation, the object only contains the host path and stations - the path structure is set by a user function call. The start time, end time and sampling rate are altered on the fly for each time step of detect.

**Comment by hemmelig** [comment]
Print string suggestion for class SeisScan:

```
def __str__(self):

    out = "QuakeMigrate scan parameters"
    out = out + "\n".join("\tTime step\t:\t{}".format(self.time_step))
    out = out + "\n\n".join("\tData sampling rate\t:\t{}".format(
        self.sampling_rate))
    out = out + "\n".join("\tOutput sampling rate\t:\t{}".format(
        self.output_sampling_rate))
    out = out + "\n\n".join("\tDecimation\t:\t[{}, {}, {}]".format(
        self.decimate[0], self.decimate[1], self.decimate[2]))
    out = out + "\n\n".join("\tBandpass filter P\t:\t[{}, {}, {}]".format(
        self.p_bp_filter[0], self.p_bp_filter[1], self.p_bp_filter[2]))
    out = out + "\n".join("\tBandpass filter S\t:\t[{}, {}, {}]".format(
        self.s_bp_filter[0], self.s_bp_filter[1], self.s_bp_filter[2]))
    out = out + "\n\n".join("\tOnset P [STA, LTA]\t:\t[{}, {}]".format(
        self.p_onset_win[0], self.p_onset_win[1]))
    out = out + "\n".join("\tOnset S [STA, LTA]\t:\t[{}, {}]".format(
        self.s_onset_win[0], self.s_onset_win[1]))
    out = out + "\n\n".join("\tPre-pad\t:\t{}".format(self.pre_pad))
    out = out + "\n".join("\tPost-pad\t:\t{}".format(self.post_pad))
    out = out + "\n\n".join("\tMarginal window\t:\t{}".format(
        self.marginal_window))
    out = out + "\n".join("\tMinimum repeat\t:\t{}".format(
        self.minimum_repeat))
    out = out + "\n".join("\tDetection threshold\t:\t{}".format(
        self.detection_threshold))
    out = out + "\n".join("\tPick threshold\t:\t{}".format(
        self.pick_threshold))
    out = out + "\n".join("\tPicking mode\t:\t{}".format(self.picking_mode))
    out = out + "\n".join("\tPercent ttime\t:\t{}".format(self.percent_tt))
    out = out + "\n".join("\tLocation error\t:\t{}".format(
        self.location_error))
    out = out + "\n\n".join("\tCentred onset\t:\t{}".format(
        self._onset_centred))
    out = out + "\n".join("\tNormalise coalescence\t:\t{}".format(
        self.normalise_coalescence))
    out = out + "\n\n".join("\tNumber of CPUs\t:\t{}".format(self.n_cores))

    return out
```

This could be improved - currently I just put out every parameter that can be set by the user with some basic grouping and formatting.
