### ISSUE TITLE
units

### ISSUE THREAD

**Issue by tmgreenfield1101** [Ulvetanna/QuakeMigrate#5]
Units should be in km not metres.

**Comment by hemmelig** [comment]
This issue has been addressed with the recent overhaul of the lookup table module. All units for QuakeMigrate are in METRES - any conversions required to move between NonLinLoc grid definitions are handled internally. The only user parameter that is in units of KILOMETRES is the optional nlloc_dx parameter when creating a lookup table using a sweep of a 2-D NLLoc lookup table.

These updates will be available with the v1.1 release. As of now (5th November 2019) they are on the "new_model" branch.
