### ISSUE TITLE
Scan - External Onset Functions

### ISSUE THREAD

**Issue by Ulvetanna** [Ulvetanna/QuakeMigrate#9]
Currently the internal compute determines the onset functions using a classic STA/LTA approach back-propagating these values and determine a coalescence value. 

The addition of external Onset functions would allow the incorporation of External Machine Learning packages (GPD, Ross et al 2018) and other onset functions e.g. Kutosis.

**Comment by hemmelig** [comment]
The generation of onset functions (as well as the autopicking function) has been separated from the core QuakeScan class to a new module (signal/onset), being replaced by callbacks to functions within the new Onset (and Pick) class. These classes can be customised by the user to experiment with different methods of onset function generation (kurtosis, GPD, etc), so long as they inherit from the abstract base class provided. This way we can ensure the new onset functions are compatible with the core QuakeScan, without the user having to dive into the heart of the code.
